services:
  - type: web
    name: poverty-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn poverty_backend.api.index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free